const PAGE_TRANSITION = 'PAGE_TRANSITION';
const GET_INNER_HEIGHT = 'GET_INNER_HEIGHT';
const TOGGLE_MENU = 'TOGGLE_MENU';
const TOGGLE_MODAL = 'TOGGLE_MODAL';
const SHOW_SMOOTH_SCROLL = 'SHOW_SMOOTH_SCROLL';
const HIDE_SMOOTH_SCROLL = 'HIDE_SMOOTH_SCROLL';
const SORT_CATEGORY = 'SORT_CATEGORY';

export default {
  PAGE_TRANSITION,
  GET_INNER_HEIGHT,
  TOGGLE_MENU,
  TOGGLE_MODAL,
  SHOW_SMOOTH_SCROLL,
  HIDE_SMOOTH_SCROLL,
  SORT_CATEGORY,
} as const;
