const PAGE_TRANSITION = 'PAGE_TRANSITION';
const GET_INNER_HEIGHT = 'GET_INNER_HEIGHT';
const TOGGLE_MENU = 'TOGGLE_MENU';
const TOGGLE_MODAL = 'TOGGLE_MODAL';
const SORT_CATEGORY = 'SORT_CATEGORY';

export default {
  PAGE_TRANSITION,
  GET_INNER_HEIGHT,
  TOGGLE_MENU,
  TOGGLE_MODAL,
  SORT_CATEGORY,
} as const;
